---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: gogs
  labels:
    app: postgres
spec:
  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        resources:
          requests:
            storage: 5Gi
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          envFrom:
            - secretRef:
                name: postgres-auth
          ports:
            - containerPort: 5432
              name: postgresdb
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
