---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: gogs
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  type: ClusterIP
  selector:
    app: postgres
