---
apiVersion: v1
kind: Service
metadata:
  name: gogs-svc
  namespace: gogs
spec:
  type: LoadBalancer
  selector:
    app: gogs
  ports:
    - name: ssh
      protocol: TCP
      port: 10022
      targetPort: 22
    - name: http
      protocol: TCP
      port: 10080
      targetPort: 3000
